sudo: required
language: cpp
compiler:
 - gcc
 - clang
script: 
 - mkdir build
 - cd build
 - cmake ..
 - make DESTDIR=next install
install:
 - sudo apt-get update
 - sudo apt-get install xorriso grub-common gcc-multilib
